language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: xaymaca@gmail.com
  password:
    secure: G2Hy/2AaS2c+xDaxThszQuNXCG0gBOqVkmbWwJG9RFV04IPLGQe3bJHH6cxK5+AbgQ9Q9AUfE3hO1sX65ocgxUz0rfC4TsF25C/WSG1x09hwBsuZ24++TYCPnL2FJRFPhI2C//5F97NoittZiDKN5P2/e+FFrG84yrzw3n9ffPWEGiKiuqQu17nGFK50a04ve83lhKTJU92FT8LLnkSchgMYJGeelr9r38Ghw3H1qSXSqGPmskSDKMX5wSE5/v4AiYhqGSHXZVDNxlrMYCW5gvycR2ILPIo8anOyyYkGWEqtoFOj/cDOaB2pP7mBf+ZyiULXJIN4CTnMKXn4uOPBOS0MXQUK8RvJP2nC9Ss/D1oMXUi5DPwAGWDOk5j/skVOr7x9CWLngkKEtaRfVhOSHuUBvM/AKUvLvJxGIMGoJ441+jNIgnPlWjoUlEdrUShrqL3mF8tcm1d1gEpgwy1AMBi/4OM90tjFf3EI5HvUYL610loD6Gw6mFOdfEBl2CeKYqp6ATLNcucGk0ANyo7a4TtqirD3pkfC+uayk4uy+MiwJkSMuLYB2FoTywrfh68OdWf3O/Q9yYk9Ti7EncTi50EIBCpB8jKbdIw7z0NVbfJbASxRUzQ4DNd5xCvME3GnDNcvbQCL9j3QPSYKv8GKPDWY/2BNiJtPJqZkWw/p9Q8=
  organization: xaymaca-studios
  space: development
  on:
    repo: vinny2020/xaymaca-boot-cf-demo
