language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  edge: true
  api: https://api.run.pivotal.io
  username: xaymaca@gmail.com
  password:
    secure: Hn1quIaiwnj/aBxdItH2khWn/WLtCyWYzMBjpR6GhSE7zlYgZVjNGTjHhTrPQ+IB3A3mPTvSH7p7V8ey+vtnZv1QtXLcgbPRCduZskgOOx6MyJznTHzREJrKvLLWokyAnaZQUAC+5UYwmOdK1O01vv38NzzBW7FUBZjnc3uPGoMCZHU+pN7z+l9tonfJ6SAEeOrT9yMs7wRL4oFpIFK/z742bhS6GEXN5TWyFV/8seFBF/gm6oCGgeZKNS9odYXS5n+GFvhrylwU0XHJthDBbXHTMzNifAc0GKSdrx4fo9AenRcRMEm/1aHCluVG06iQTrqW2ps8FJuiPrPqHwSfgVNoUrHzyup9BMLVjDiEjoTT88rGIt4+D5HEC6ftR/cI+LvA7WLIyuBK7XsuKPKyOYgVnRPDSSdOfPZZQ9hkJ5E6S5o4kmoXwmlYDu+sqV4IIkWxSgCw13fABS9oAzvfTxWAvqSSge/rw8IGARloLu2IVXY3cWmyzk+vk7395FkECOPRtaEa0bp2k7ZaqJmS73wRcVx7faqtGHUUlOoh02YPfLZjgxeV0veGb+dwvotC55aJ46GjMOS4QoX+tI1nuRkuZy8/0TwlngamGTnrBFIi3MwuNG4lMhDADFzleonLvMHj3hN7X0k0uXNTqWt7Md8n1KlZTRXXM5qZgR/sijs=
  organization: xaymaca-studios
  space: development
  on:
    repo: vinny2020/xaymaca-boot-cf-demo
